version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    environment:
      DEPLOY_ENV: dev

    working_dir: /home/node/
    volumes:
      - "./src:/home/node/src"
      - "./test:/home/node/test"
    entrypoint:
      - /bin/sh
      - -c
      - |
        ./entrypoint.sh
    ports:
      - "8080:8080"
    networks:
      - default

